[native_configs]

[rayon_configs]

[tokio_configs.axum1]
worker_threads = 8
max_blocking_threads = 1
core_allocation.DedicatedCoreSet = { min = 0, max = 8 }

[tokio_configs.axum2]
worker_threads = 8
max_blocking_threads = 1
core_allocation.DedicatedCoreSet = { min = 0, max = 8 }
